# Generated by Django 5.2.7 on 2025-10-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('subscriber', 'Subscriber'), ('moderator', 'Moderator'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
